name: ci-cd
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/**"
    branches:
      - "main"
      - "develop"

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout cureent repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build kotlin project
        shell: bash
        run: ./gradlew build
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Test & Build Docker image
        uses: docker/build-push-action@v3
        env:
          IMAGE_REGISTRY: ${{ secrets.ONE_LINE_REGISTRY }}
          IMAGE_REPOSITORY: ${{ secrets.ONE_LINE_REPOSITORY }}
          IMAGE_TAG: "dev"
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Push jar file for Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ONE_LINE_HOST }}
          username: ${{ secrets.ONE_LINE_USERNAME }}
          password: ${{ secrets.ONE_LINE_PASSWORD }}
          port: ${{ secrets.ONE_LINE_PORT }}
          source: "build/libs/one-line-server-0.0.1-SNAPSHOT.jar"
          target: "/workspace/one-line-hc"


